# Generated by Django 4.2.7 on 2025-07-23 20:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the member', max_length=100)),
                ('email', models.EmailField(help_text='Email address for communication', max_length=254, unique=True)),
                ('mobile_phone', models.CharField(help_text='Contact number', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('date_of_birth', models.DateField(help_text='Date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('address', models.TextField(help_text='Complete address')),
                ('member_since', models.DateField(default=django.utils.timezone.now, help_text='Date when member joined')),
                ('membership_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('expiry_date', models.DateField(help_text='Membership expiry date')),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='Total membership fee', max_digits=10)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount pending', max_digits=10)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is membership active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='member_photos/')),
            ],
            options={
                'verbose_name': 'Gym Member',
                'verbose_name_plural': 'Gym Members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('cheque', 'Cheque')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='members.member')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'ordering': ['-payment_date'],
            },
        ),
    ]
