# Generated by Django 4.2.7 on 2025-07-23 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Membership expiry date (auto-calculated if not provided)', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_since',
            field=models.DateField(default=datetime.date.today, help_text='Date when member joined'),
        ),
    ]
