# Generated by Django 4.2.7 on 2025-07-30 12:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_expiry_date_alter_member_member_since'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the visitor', max_length=100)),
                ('phone', models.CharField(help_text='Contact number', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, null=True)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('converted', 'Converted'), ('not_interested', 'Not Interested')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('walk_in', 'Walk-in'), ('referral', 'Referral'), ('online', 'Online'), ('advertisement', 'Advertisement'), ('social_media', 'Social Media'), ('other', 'Other')], default='walk_in', max_length=20)),
                ('interest_level', models.IntegerField(default=5, help_text='Interest level from 1-10 (10 being highest)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the lead', null=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateField(blank=True, help_text='Next follow-up date', null=True)),
                ('conversion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_member', models.ForeignKey(blank=True, help_text='If converted, link to the member record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
