# Generated by Django 4.2.7 on 2025-07-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, help_text='Complete address (optional)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for communication (optional)', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile_phone',
            field=models.CharField(help_text='Contact number', max_length=15),
        ),
    ]
