# Generated by Django 4.2.7 on 2025-08-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_address_alter_member_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobile_phone',
            field=models.CharField(blank=True, help_text='Contact number (optional)', max_length=15, null=True),
        ),
    ]
