# Generated by Django 4.2.7 on 2025-09-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_mobile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('half_yearly', 'Half-Yearly'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
    ]
