# Generated by Django 4.2.7 on 2025-09-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_update_quarterly_to_half_yearly_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('half_yearly', 'Half-Yearly'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
    ]
