# Generated by Django 4.2.7 on 2025-09-03 15:52

from django.db import migrations

def update_weekly_to_quarterly(apps, schema_editor):
    Member = apps.get_model('members', 'Member')
    # Update all existing weekly memberships to quarterly
    Member.objects.filter(membership_type='weekly').update(membership_type='quarterly')

def reverse_update(apps, schema_editor):
    Member = apps.get_model('members', 'Member')
    # Reverse operation if needed
    Member.objects.filter(membership_type='quarterly').update(membership_type='weekly')

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_change_weekly_to_quarterly'),
    ]

    operations = [
        migrations.RunPython(update_weekly_to_quarterly, reverse_update),
    ]
